// DOM_PROJECT/vue/app.vue
<!-- App.vue -->
<script setup>
import { ref } from 'vue'

const priorities = ['Low', 'Medium', 'High']

const tasks = ref([])
const newTaskName = ref('')
const newTaskPriority = ref('Medium')

const editingId = ref(null)
const editName = ref('')
const editPriority = ref('Medium')

// --- Add a task ---
const addTask = () => {
  const name = newTaskName.value.trim()
  if (!name) return
  tasks.value.push({
    id: Date.now(),
    name,
    priority: newTaskPriority.value
  })
  newTaskName.value = ''
  newTaskPriority.value = 'Medium'
}

// --- Remove a task ---
const removeTask = (id) => {
  const index = tasks.value.findIndex(t => t.id === id)
  if (index !== -1) tasks.value.splice(index, 1)
  if (editingId.value === id) editingId.value = null
}

// --- Start editing ---
const startEditing = (task) => {
  editingId.value = task.id
  editName.value = task.name
  editPriority.value = task.priority
}

// --- Save edit ---
const saveEdit = (id) => {
  const task = tasks.value.find(t => t.id === id)
  if (task) {
    task.name = editName.value.trim() || task.name
    task.priority = editPriority.value
  }
  editingId.value = null
}

// --- Cancel edit ---
const cancelEdit = () => {
  editingId.value = null
}
</script>

<template>
  <div class="app">
    <h1>Todo List (Vue)</h1>

    <!-- Add task form -->
    <div class="add-task">
      <input
        type="text"
        placeholder="Task name"
        v-model="newTaskName"
        @keyup.enter="addTask"
      />
      <select v-model="newTaskPriority">
        <option v-for="p in priorities" :key="p" :value="p">{{ p }}</option>
      </select>
      <button @click="addTask">Add Task</button>
    </div>

    <!-- Task list -->
    <ul class="task-list">
      <li v-for="task in tasks" :key="task.id" class="task-item">
        <!-- Editing mode -->
        <div v-if="editingId === task.id" class="edit-mode">
          <input type="text" v-model="editName" />
          <select v-model="editPriority">
            <option v-for="p in priorities" :key="p" :value="p">{{ p }}</option>
          </select>
          <button @click="saveEdit(task.id)">Save</button>
          <button @click="cancelEdit">Cancel</button>
        </div>

        <!-- View mode -->
        <div v-else class="view-mode">
          <span class="task-name">{{ task.name }}</span>
          <span
            class="priority"
            :class="'priority-' + task.priority.toLowerCase()"
          >
            {{ task.priority }}
          </span>
          <button @click="startEditing(task)">Edit</button>
          <button @click="removeTask(task.id)">Delete</button>
        </div>
      </li>
    </ul>
  </div>
</template>

<style scoped>
.app {
  max-width: 500px;
  margin: 2rem auto;
  font-family: sans-serif;
}
.add-task {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1rem;
}
.task-list {
  list-style: none;
  padding: 0;
}
.task-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 0;
  border-bottom: 1px solid #eee;
}
.priority {
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  font-size: 0.8rem;
  color: white;
}
.priority-low { background: #6c757d; }
.priority-medium { background: #fd7e14; }
.priority-high { background: #dc3545; }
.view-mode, .edit-mode {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: 100%;
}
.task-name {
  flex-grow: 1;
}
</style>

// DOM_PROJECT/svelte/App.svelte
<!-- App.svelte -->
<script>
  let tasks = [];
  let newTaskName = '';
  let newTaskPriority = 'Medium';
  const priorities = ['Low', 'Medium', 'High'];

  let editingId = null;
  let editName = '';
  let editPriority = 'Medium';

  // --- Add a task ---
  function addTask() {
    const name = newTaskName.trim();
    if (!name) return;
    tasks = [
      ...tasks,
      { id: Date.now(), name, priority: newTaskPriority }
    ];
    newTaskName = '';
    newTaskPriority = 'Medium';
  }

  // --- Remove a task ---
  function removeTask(id) {
    tasks = tasks.filter(t => t.id !== id);
    if (editingId === id) editingId = null;
  }

  // --- Start editing ---
  function startEditing(task) {
    editingId = task.id;
    editName = task.name;
    editPriority = task.priority;
  }

  // --- Save edit ---
  function saveEdit(id) {
    tasks = tasks.map(t => {
      if (t.id === id) {
        return {
          ...t,
          name: editName.trim() || t.name,
          priority: editPriority
        };
      }
      return t;
    });
    editingId = null;
  }

  // --- Cancel edit ---
  function cancelEdit() {
    editingId = null;
  }

  // --- Handle Enter key for add ---
  function handleKeydown(event) {
    if (event.key === 'Enter') addTask();
  }
</script>

<div class="app">
  <h1>Todo List (Svelte)</h1>

  <!-- Add task form -->
  <div class="add-task">
    <input
      type="text"
      placeholder="Task name"
      bind:value={newTaskName}
      on:keydown={handleKeydown}
    />
    <select bind:value={newTaskPriority}>
      {#each priorities as p}
        <option value={p}>{p}</option>
      {/each}
    </select>
    <button on:click={addTask}>Add Task</button>
  </div>

  <!-- Task list -->
  <ul class="task-list">
    {#each tasks as task (task.id)}
      <li class="task-item">
        {#if editingId === task.id}
          <!-- Editing mode -->
          <div class="edit-mode">
            <input type="text" bind:value={editName} />
            <select bind:value={editPriority}>
              {#each priorities as p}
                <option value={p}>{p}</option>
              {/each}
            </select>
            <button on:click={() => saveEdit(task.id)}>Save</button>
            <button on:click={cancelEdit}>Cancel</button>
          </div>
        {:else}
          <!-- View mode -->
          <div class="view-mode">
            <span class="task-name">{task.name}</span>
            <span class="priority priority-{task.priority.toLowerCase()}">
              {task.priority}
            </span>
            <button on:click={() => startEditing(task)}>Edit</button>
            <button on:click={() => removeTask(task.id)}>Delete</button>
          </div>
        {/if}
      </li>
    {/each}
  </ul>
</div>

<style>
  .app {
    max-width: 500px;
    margin: 2rem auto;
    font-family: sans-serif;
  }
  .add-task {
    display: flex;
    gap: 0.5rem;
    margin-bottom: 1rem;
  }
  .task-list {
    list-style: none;
    padding: 0;
  }
  .task-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem 0;
    border-bottom: 1px solid #eee;
  }
  .priority {
    padding: 0.2rem 0.5rem;
    border-radius: 4px;
    font-size: 0.8rem;
    color: white;
  }
  .priority-low { background: #6c757d; }
  .priority-medium { background: #fd7e14; }
  .priority-high { background: #dc3545; }
  .view-mode, .edit-mode {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    width: 100%;
  }
  .task-name {
    flex-grow: 1;
  }
</style>
